[theme]
# Primary accent color for interactive elements.
primaryColor= "#d33682"

#background color for the main content area.
backgroundColor = "#002b36"

# Background color used for the sidebar and most interactive widget
secondaryBackgroundColor = "#586e75"

# Color used for almost all text.
textColor = "#fff"

[client]
toolbarMode = "minimal"